path_working_directory          = '<path_working_directory>'
path_analysis_working_directory = '<path_analysis_working_directory>'
path_samples                    = '<path_samples>'
path_samples_user_defined       = '<path_samples_user_defined>'
path_cache                      = '<path_cache>'
path_voms_proxy                 = '<path_voms_proxy>'